version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  migration:
    image: people-manager-migration-repo:latest
    entrypoint: /bin/sh -c
    command: 
      - NODE_ENV=production yarn db-migrate
      # - yarn add ts-node && yarn migrate
      # - ts-node
      # - -D
      # - && yarn migrate
    volumes:
      - ./packages/backend/env:/env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_CONNECTION_URL=postgres://citizix_user:S3cret@postgres:5432/citizix_db
      - BACKEND_URL=http://localhost:3001
      - FRONTEND_URL=http://localhost:3001
      - BACKEND_PORT=3001
  app:
    image: people-manager-repo:latest
    ports:
      - 3001:3001
    # entrypoint: /bin/sh -c
    command: /env/.env.docker.local
    volumes:
      - ./packages/backend/env:/env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_CONNECTION_URL=postgres://citizix_user:S3cret@postgres:5432/citizix_db
      - BACKEND_URL=http://localhost:3001
      - FRONTEND_URL=http://localhost:3001
      - BACKEND_PORT=3001
