import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import Schedule from 'backend/models/schedule/schedule';
import Shift from 'backend/models/shift/shift';
import User from 'backend/models/user/user';
import ShiftViewModel, {
  SHIFT_SIGNUP_RESTRICTION_MESSAGES,
} from 'backend/view_models/shift';
import SignupStatus, {
  NewPlaceholderSignupStatus,
} from 'backend/view_models/signup_status';
import { MutableSnapshot, RecoilRoot } from 'recoil';
import BackendShiftClient from '../../api/shifts/shifts';
import { UserState } from '../../state/store';
import {
  GeneratedSignupShift,
  adminRemainingShiftCount,
  eligibleAdminAssignees,
  generatedSignupShift,
  SignupCategory,
  SignupSlots,
  signupRequirementChip,
  toggleAdminParticipantSelection,
  toggleShiftSelection,
} from './ShiftDisplay';

function generatedSchedule(
  kind: 'chore' | 'event' | 'dinner',
  name: string,
): Schedule {
  const schedule = new Schedule(12, name, 'Generated schedule');
  schedule.chorePlanID = 4;
  schedule.plannerKey = `${kind}|${name}`;
  return schedule;
}

function adminSignupStatus(
  id: number,
  firstName: string,
  lastName: string,
  counts: { chore: number; event: number; dinner: number },
): SignupStatus {
  const status = NewPlaceholderSignupStatus();
  status.user = User.fromJson({ id, firstName, lastName });
  status.hasSignedUpForRoster = true;
  status.requirements = { chore: 3, event: 1, dinner: 1 };
  status.choreShiftCount = counts.chore;
  status.eventShiftCount = counts.event;
  status.dinnerShiftCount = counts.dinner;
  status.shiftCount = counts.chore + counts.event + counts.dinner;
  return status;
}

function shiftViewModel(
  plannerKey: string,
  id = 34,
  startTime = new Date('2026-08-23T15:00:00.000Z'),
): ShiftViewModel {
  const shift = new Shift(
    id,
    12,
    startTime,
    new Date(startTime.getTime() + 60 * 60 * 1000),
    2,
  );
  shift.plannerKey = plannerKey;
  return {
    shift,
    scheduleName: 'Kitchen cleanup',
    participants: [],
    signupOpen: false,
  };
}

function choreSignupShift(
  name: string,
  day: number,
  id: number,
  participants: User[] = [],
): GeneratedSignupShift {
  const generatedShift = generatedSignupShift(
    generatedSchedule('chore', name),
    {
      ...shiftViewModel(
        `chore|${day}|${name}`,
        id,
        new Date(Date.UTC(2026, 7, 22 + day, 15)),
      ),
      participants,
      signupOpen: true,
    },
  );

  if (!generatedShift) {
    throw new Error('Expected a generated signup shift.');
  }
  return generatedShift;
}

function renderSignupCategory(
  currentUser: User,
  shifts: GeneratedSignupShift[],
  shiftClient: BackendShiftClient,
  onSignupComplete: () => Promise<void>,
) {
  const signupCategory = React.createElement(SignupCategory, {
    allShifts: shifts,
    kind: 'chore',
    requirement: 3,
    onSignupComplete,
    shiftClient,
    shifts,
  });
  const TestRecoilRoot = RecoilRoot as React.ComponentType<{
    children?: React.ReactNode;
    initializeState: (mutableSnapshot: MutableSnapshot) => void;
  }>;
  render(
    React.createElement(
      TestRecoilRoot,
      { initializeState: ({ set }) => set(UserState, currentUser) },
      signupCategory,
    ),
  );
}

test('maps a generated chore shift into the signup sheet grid', () => {
  const result = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    shiftViewModel('chore|1|Kitchen cleanup'),
  );

  expect(result).toMatchObject({
    kind: 'chore',
    scheduleName: 'Kitchen cleanup',
    day: 1,
    timePeriod: '8:00 AM',
    periodOrder: 0,
  });
});

test('preserves an event shift time period and column order', () => {
  const result = generatedSignupShift(
    generatedSchedule('event', 'Kitchen cleanup'),
    shiftViewModel('event|3|2|2p-6p|Kitchen cleanup'),
  );

  expect(result).toMatchObject({
    kind: 'event',
    day: 3,
    timePeriod: '2p-6p',
    periodOrder: 2,
  });
});

test('maps a dinner shift to its assigned day and time', () => {
  const result = generatedSignupShift(
    generatedSchedule('dinner', 'Dinner prep'),
    shiftViewModel('dinner|5|4:30 PM|Dinner prep'),
  );

  expect(result).toMatchObject({
    kind: 'dinner',
    scheduleName: 'Dinner prep',
    day: 5,
    timePeriod: '4:30 PM',
    periodOrder: 0,
  });
});

test('ignores schedules that were not generated by the chore planner', () => {
  const schedule = new Schedule(12, 'Kitchen cleanup', 'Legacy schedule');

  expect(
    generatedSignupShift(schedule, shiftViewModel('chore|1|Kitchen cleanup')),
  ).toBeNull();
});

test('adds and removes shift selections without exceeding the table limit', () => {
  expect(toggleShiftSelection([10, 11], 12, 3)).toEqual([10, 11, 12]);
  expect(toggleShiftSelection([10, 11, 12], 13, 3)).toEqual([10, 11, 12]);
  expect(toggleShiftSelection([10, 11, 12], 11, 3)).toEqual([10, 12]);
});

test('selects at most two distinct people for admin reassignment', () => {
  const leslie = {
    shiftID: 10,
    userID: 7,
    participantName: 'Leslie Knope',
    shiftDescription: 'Kitchen, day 1, 8:00 AM',
  };
  const ben = {
    shiftID: 11,
    userID: 8,
    participantName: 'Ben Wyatt',
    shiftDescription: 'Trash, day 1, 9:00 AM',
  };
  const ron = {
    shiftID: 12,
    userID: 9,
    participantName: 'Ron Swanson',
    shiftDescription: 'Ice, day 1, 10:00 AM',
  };
  const leslieInAnotherShift = {
    ...leslie,
    shiftID: 13,
    shiftDescription: 'Gate, day 2, 10:00 AM',
  };

  expect(toggleAdminParticipantSelection([], leslie)).toEqual([leslie]);
  expect(
    toggleAdminParticipantSelection([leslie], leslieInAnotherShift),
  ).toEqual([leslie]);
  expect(toggleAdminParticipantSelection([leslie], ben)).toEqual([leslie, ben]);
  expect(toggleAdminParticipantSelection([leslie, ben], ron)).toEqual([
    leslie,
    ben,
  ]);
  expect(toggleAdminParticipantSelection([leslie, ben], leslie)).toEqual([ben]);
});

test('lists only roster people who still need required shifts', () => {
  const complete = adminSignupStatus(7, 'Leslie', 'Knope', {
    chore: 3,
    event: 1,
    dinner: 1,
  });
  const needsDinner = adminSignupStatus(8, 'Ben', 'Wyatt', {
    chore: 3,
    event: 1,
    dinner: 0,
  });
  const needsChores = adminSignupStatus(9, 'April', 'Ludgate', {
    chore: 1,
    event: 1,
    dinner: 1,
  });

  expect(eligibleAdminAssignees([complete, needsDinner, needsChores])).toEqual([
    needsChores,
    needsDinner,
  ]);
  expect(adminRemainingShiftCount(needsChores, 'chore')).toBe(2);
  expect(adminRemainingShiftCount(needsChores, 'event')).toBe(0);
});

test('shows how many shifts the current user still needs after signups open', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const signedUpShift = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    {
      ...shiftViewModel('chore|1|Kitchen cleanup'),
      participants: [currentUser],
      signupOpen: true,
    },
  );
  const openShift = generatedSignupShift(
    generatedSchedule('chore', 'Trash patrol'),
    {
      ...shiftViewModel('chore|2|Trash patrol'),
      signupOpen: true,
    },
  );

  if (!signedUpShift || !openShift) {
    throw new Error('Expected generated signup shifts.');
  }

  expect(
    signupRequirementChip(
      'chore',
      [signedUpShift, openShift],
      currentUser.id,
      3,
    ),
  ).toEqual({ label: '2 shifts required!', color: 'warning' });
});

test('uses singular wording when one shift is still required', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const signedUpShifts = [1, 2].map((day) => {
    const name = `Chore ${day}`;
    return generatedSignupShift(generatedSchedule('chore', name), {
      ...shiftViewModel(`chore|${day}|${name}`),
      participants: [currentUser],
      signupOpen: true,
    });
  });

  if (signedUpShifts.some((shift) => !shift)) {
    throw new Error('Expected generated signup shifts.');
  }

  expect(
    signupRequirementChip(
      'chore',
      signedUpShifts as NonNullable<(typeof signedUpShifts)[number]>[],
      currentUser.id,
      3,
    ),
  ).toEqual({ label: '1 shift required!', color: 'warning' });
});

test('shows a green confirmation when the shift requirement is complete', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const signedUpShift = generatedSignupShift(
    generatedSchedule('dinner', 'Dinner prep'),
    {
      ...shiftViewModel('dinner|5|4:30 PM|Dinner prep'),
      participants: [currentUser],
      signupOpen: true,
    },
  );

  if (!signedUpShift) {
    throw new Error('Expected a generated signup shift.');
  }

  expect(
    signupRequirementChip('dinner', [signedUpShift], currentUser.id, 1),
  ).toEqual({ label: 'Requirement complete!', color: 'success' });
});

test('shows when a category is not required for the current user', () => {
  const openShift = choreSignupShift('Kitchen cleanup', 1, 34);

  expect(signupRequirementChip('chore', [openShift], 7, 0)).toEqual({
    label: 'Daily chores not required',
    color: 'success',
  });
});

test('does not show a shift requirement before signups open', () => {
  const closedShift = generatedSignupShift(
    generatedSchedule('event', 'Gate crew'),
    shiftViewModel('event|1|0|10a-2p|Gate crew'),
  );

  if (!closedShift) {
    throw new Error('Expected a generated signup shift.');
  }

  expect(signupRequirementChip('event', [closedShift], 7, 3)).toEqual({
    label: 'Signups not open yet',
    color: 'default',
  });
});

test('labels a closed category as closed', () => {
  const closedShift = generatedSignupShift(
    generatedSchedule('event', 'Gate crew'),
    {
      ...shiftViewModel('event|1|0|10a-2p|Gate crew'),
      chorePlanStatus: 'closed',
    },
  );

  if (!closedShift) {
    throw new Error('Expected generated signup shifts.');
  }

  expect(signupRequirementChip('event', [closedShift], 7, 3)).toEqual({
    label: 'Signups closed',
    color: 'default',
  });
});

test('disables removal after the chore plan is closed', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const closedShift = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    {
      ...shiftViewModel('chore|1|Kitchen cleanup'),
      chorePlanStatus: 'closed',
      participants: [currentUser],
      signupOpen: false,
    },
  );

  if (!closedShift) {
    throw new Error('Expected a generated signup shift.');
  }
  renderSignupCategory(
    currentUser,
    [closedShift],
    new BackendShiftClient(''),
    jest.fn().mockResolvedValue(undefined),
  );

  expect(
    screen.getByRole('button', {
      name: /remove your spot for kitchen cleanup/i,
    }),
  ).toBeDisabled();
  expect(
    screen.queryByRole('button', { name: 'Remove shift' }),
  ).not.toBeInTheDocument();
});

test('renders the current user slot as a removal selector', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const signedUpUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const generatedShift = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    {
      ...shiftViewModel('chore|1|Kitchen cleanup'),
      participants: [signedUpUser],
      signupOpen: true,
    },
  );
  const onToggleRemoval = jest.fn();

  if (!generatedShift) {
    throw new Error('Expected a generated signup shift.');
  }
  render(
    React.createElement(SignupSlots, {
      currentUserID: currentUser.id,
      onToggleRemoval,
      onToggleSignup: jest.fn(),
      removalDisabled: false,
      removalSelected: true,
      selectionDisabled: false,
      selectionDisabledReason: null,
      shift: generatedShift,
      signupSelected: false,
    }),
  );

  const removalSlot = screen.getByRole('button', {
    name: /keep your spot for kitchen cleanup/i,
  });
  expect(removalSlot).toHaveAttribute('aria-pressed', 'true');
  expect(removalSlot).toHaveClass('removal-selected');

  fireEvent.click(removalSlot);
  expect(onToggleRemoval).toHaveBeenCalledWith(
    generatedShift.shiftViewModel.shift.id,
  );
});

test('marks other users separately from the logged-in user', () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const otherUser = User.fromJson({
    id: 8,
    firstName: 'Ben',
    lastName: 'Wyatt',
  });
  const generatedShift = choreSignupShift('Kitchen cleanup', 1, 34, [
    currentUser,
    otherUser,
  ]);

  render(
    React.createElement(SignupSlots, {
      currentUserID: currentUser.id,
      onToggleRemoval: jest.fn(),
      onToggleSignup: jest.fn(),
      removalDisabled: false,
      removalSelected: false,
      selectionDisabled: false,
      shift: generatedShift,
      signupSelected: false,
    }),
  );

  expect(
    screen.getByRole('button', {
      name: /remove your spot for kitchen cleanup/i,
    }),
  ).toHaveClass('current-user');
  expect(screen.getByText('Ben W.')).toHaveClass('other-user');
});

test('makes individual people and move destinations selectable in Admin Edit mode', () => {
  const participant = User.fromJson({
    id: 8,
    firstName: 'Ben',
    lastName: 'Wyatt',
  });
  const generatedShift = choreSignupShift('Kitchen cleanup', 1, 34, [
    participant,
  ]);
  const onToggleAdminParticipant = jest.fn();
  const onToggleAdminDestination = jest.fn();

  render(
    React.createElement(SignupSlots, {
      adminEditMode: true,
      adminDestinationShiftID: null,
      currentUserID: 7,
      onToggleAdminDestination,
      onToggleAdminParticipant,
      onToggleRemoval: jest.fn(),
      onToggleSignup: jest.fn(),
      removalDisabled: false,
      removalSelected: false,
      selectionDisabled: false,
      selectedAdminParticipants: [
        {
          shiftID: 99,
          userID: 7,
          participantName: 'Leslie Knope',
          shiftDescription: 'Trash patrol, day 1, 9:00 AM',
        },
      ],
      shift: generatedShift,
      signupSelected: false,
    }),
  );

  const personSelector = screen.getByRole('button', {
    name: /select ben w\. in kitchen cleanup.*for admin shift editing/i,
  });
  const destinationSelector = screen.getByRole('button', {
    name: /select kitchen cleanup.*as move destination/i,
  });
  expect(personSelector).toHaveAttribute('aria-pressed', 'false');
  expect(destinationSelector).toHaveAttribute('aria-pressed', 'false');
  expect(
    screen.queryByRole('button', { name: /open spot/i }),
  ).not.toBeInTheDocument();
  expect(screen.getByText('Open spot').tagName).toBe('SPAN');
  expect(
    screen.queryByRole('button', { name: /remove your spot/i }),
  ).not.toBeInTheDocument();

  fireEvent.click(personSelector);
  expect(onToggleAdminParticipant).toHaveBeenCalledWith(
    expect.objectContaining({ shiftID: 34, userID: 8 }),
  );
  fireEvent.click(destinationSelector);
  expect(onToggleAdminDestination).toHaveBeenCalledWith(34);
});

test('adds a selected roster person through an open Admin Edit slot', () => {
  const assignee = adminSignupStatus(9, 'April', 'Ludgate', {
    chore: 1,
    event: 1,
    dinner: 1,
  });
  const generatedShift = choreSignupShift('Kitchen cleanup', 1, 34);
  const onAdminAssign = jest.fn();

  render(
    React.createElement(SignupSlots, {
      adminAssignee: assignee,
      adminEditMode: true,
      currentUserID: 7,
      onAdminAssign,
      onToggleRemoval: jest.fn(),
      onToggleSignup: jest.fn(),
      removalDisabled: false,
      removalSelected: false,
      selectionDisabled: false,
      shift: generatedShift,
      signupSelected: false,
    }),
  );

  fireEvent.click(
    screen.getByRole('button', {
      name: /add april l\. to kitchen cleanup, day 1/i,
    }),
  );
  expect(onAdminAssign).toHaveBeenCalledWith(generatedShift);
});

test.each([
  [
    'an existing shift conflict',
    SHIFT_SIGNUP_RESTRICTION_MESSAGES.existingShiftConflict,
  ],
  [
    'the estimated attendance window',
    SHIFT_SIGNUP_RESTRICTION_MESSAGES.outsideAttendanceWindow,
  ],
])('explains disabled signup spots caused by %s', async (_label, reason) => {
  const generatedShift = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    {
      ...shiftViewModel('chore|1|Kitchen cleanup'),
      signupOpen: true,
      signupRestrictionReason: reason,
    },
  );

  if (!generatedShift) {
    throw new Error('Expected a generated signup shift.');
  }
  render(
    React.createElement(SignupSlots, {
      currentUserID: 7,
      onToggleRemoval: jest.fn(),
      onToggleSignup: jest.fn(),
      removalDisabled: false,
      removalSelected: false,
      selectionDisabled: true,
      selectionDisabledReason: reason,
      shift: generatedShift,
      signupSelected: false,
    }),
  );

  const openSpot = screen.getAllByRole('button', {
    name: /select open spot for kitchen cleanup/i,
  })[0];
  expect(openSpot).toBeDisabled();

  fireEvent.mouseOver(openSpot.parentElement as HTMLElement);
  expect(await screen.findByRole('tooltip')).toHaveTextContent(reason);
});

test('submits selected signups through the atomic edit endpoint', async () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
  });
  const shift = choreSignupShift('Kitchen cleanup', 1, 34);
  const shiftClient = new BackendShiftClient('');
  const editSignup = jest
    .spyOn(shiftClient, 'EditChoreSignup')
    .mockResolvedValue({ addedShiftIDs: [34], removedShiftIDs: [] });
  const onSignupComplete = jest.fn().mockResolvedValue(undefined);
  renderSignupCategory(currentUser, [shift], shiftClient, onSignupComplete);

  fireEvent.click(
    screen.getAllByRole('button', {
      name: /select open spot for kitchen cleanup/i,
    })[0],
  );
  fireEvent.click(screen.getByRole('button', { name: 'Sign up (1)' }));

  await waitFor(() => {
    expect(editSignup).toHaveBeenCalledWith([34], []);
    expect(onSignupComplete).toHaveBeenCalledTimes(1);
  });
});

test('removes the selected current-user shift and refreshes the sheet', async () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const signedUpUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const generatedShift = generatedSignupShift(
    generatedSchedule('chore', 'Kitchen cleanup'),
    {
      ...shiftViewModel('chore|1|Kitchen cleanup'),
      participants: [signedUpUser],
      signupOpen: true,
    },
  );
  const shiftClient = new BackendShiftClient('');
  const editSignup = jest
    .spyOn(shiftClient, 'EditChoreSignup')
    .mockResolvedValue({ addedShiftIDs: [], removedShiftIDs: [34] });
  const onSignupComplete = jest.fn().mockResolvedValue(undefined);

  if (!generatedShift) {
    throw new Error('Expected a generated signup shift.');
  }
  renderSignupCategory(
    currentUser,
    [generatedShift],
    shiftClient,
    onSignupComplete,
  );

  fireEvent.click(
    screen.getByRole('button', {
      name: /remove your spot for kitchen cleanup/i,
    }),
  );
  fireEvent.click(screen.getByRole('button', { name: 'Remove shift' }));

  await waitFor(() => {
    expect(editSignup).toHaveBeenCalledWith(
      [],
      [generatedShift.shiftViewModel.shift.id],
    );
    expect(onSignupComplete).toHaveBeenCalledTimes(1);
  });
  expect(await screen.findByText('Removed your chore shift.')).toBeVisible();
});

test('removes multiple selected current-user shifts together', async () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const signedUpUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const shifts = [
    choreSignupShift('Kitchen cleanup', 1, 34, [signedUpUser]),
    choreSignupShift('Trash patrol', 2, 35, [signedUpUser]),
  ];
  const shiftClient = new BackendShiftClient('');
  const editSignup = jest
    .spyOn(shiftClient, 'EditChoreSignup')
    .mockResolvedValue({ addedShiftIDs: [], removedShiftIDs: [34, 35] });
  const onSignupComplete = jest.fn().mockResolvedValue(undefined);
  renderSignupCategory(currentUser, shifts, shiftClient, onSignupComplete);

  fireEvent.click(
    screen.getByRole('button', {
      name: /remove your spot for kitchen cleanup/i,
    }),
  );
  fireEvent.click(
    screen.getByRole('button', {
      name: /remove your spot for trash patrol/i,
    }),
  );
  fireEvent.click(screen.getByRole('button', { name: 'Remove shifts (2)' }));

  await waitFor(() => {
    expect(editSignup).toHaveBeenCalledTimes(1);
    expect(editSignup).toHaveBeenCalledWith([], [34, 35]);
    expect(onSignupComplete).toHaveBeenCalledTimes(1);
  });
  expect(await screen.findByText('Removed 2 chore shifts.')).toBeVisible();
});

test('atomically changes a current shift to an open replacement', async () => {
  const currentUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const signedUpUser = User.fromJson({
    id: 7,
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });
  const shifts = [
    choreSignupShift('Kitchen cleanup', 1, 34, [signedUpUser]),
    choreSignupShift('Trash patrol', 2, 35, [signedUpUser]),
    choreSignupShift('Greeter', 3, 36, [signedUpUser]),
    choreSignupShift('Replacement', 1, 37),
  ];
  shifts[3].shiftViewModel.signupRestrictionReason =
    SHIFT_SIGNUP_RESTRICTION_MESSAGES.existingShiftConflict;
  shifts[3].shiftViewModel.signupConflictShiftIDs = [34];
  const shiftClient = new BackendShiftClient('');
  const unregister = jest.spyOn(shiftClient, 'UnregisterFromShift');
  const signup = jest.spyOn(shiftClient, 'SignUpForShifts');
  const change = jest
    .spyOn(shiftClient, 'EditChoreSignup')
    .mockResolvedValue({ addedShiftIDs: [37], removedShiftIDs: [34] });
  const onSignupComplete = jest.fn().mockResolvedValue(undefined);
  renderSignupCategory(currentUser, shifts, shiftClient, onSignupComplete);

  const replacementSpot = screen.getAllByRole('button', {
    name: /select open spot for replacement/i,
  })[0];
  expect(replacementSpot).toBeDisabled();

  fireEvent.click(
    screen.getByRole('button', {
      name: /remove your spot for kitchen cleanup/i,
    }),
  );
  expect(replacementSpot).toBeEnabled();
  expect(
    screen.getByText(
      'Select one open chore shift as your replacement. Your current spot is kept unless the change succeeds.',
    ),
  ).toBeVisible();

  fireEvent.click(replacementSpot);
  fireEvent.click(screen.getByRole('button', { name: 'Change shift' }));

  await waitFor(() => {
    expect(change).toHaveBeenCalledWith([37], [34]);
    expect(onSignupComplete).toHaveBeenCalledTimes(1);
  });
  expect(unregister).not.toHaveBeenCalled();
  expect(signup).not.toHaveBeenCalled();
  expect(await screen.findByText('Changed your chore shift.')).toBeVisible();
});

test('formats a signup name with playa name, first name, and last initial', () => {
  const user = User.fromJson({
    firstName: 'Leslie',
    lastName: 'Knope',
    playaName: 'Waffles',
  });

  expect(user.shiftSignupName()).toBe('Waffles (Leslie K.)');
});

test('formats a signup name without an empty playa name', () => {
  const user = User.fromJson({
    firstName: 'Ben',
    lastName: 'Wyatt',
    playaName: '  ',
  });

  expect(user.shiftSignupName()).toBe('Ben W.');
});
