FROM node:20-alpine as builder

# Create app directory
WORKDIR /usr/src/app

RUN apk update && apk add bash curl

RUN mkdir -p /usr/local/certs/ca-certificates
RUN curl -ks 'https://truststore.pki.rds.amazonaws.com/us-west-2/us-west-2-bundle.pem' -o '/usr/local/certs/ca-certificates/us-west-2-bundle.pem'

# Install app dependencies
COPY . .

RUN yarn install
