name: Run DB Migrations

on:
  workflow_dispatch:

jobs:
  db_migrations:
    name: Run DB Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Linux Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Yarn and Dependencies
        working-directory: packages/backend
        run: |
          npm install -g yarn
          yarn install

      - name: Run Migrations
        run: ./scripts/run-migrations.sh
