name: test-and-lint
on:
  push:
    branches:
      - 'master'
      - 're-init'
  pull_request:
  workflow_dispatch:

jobs:
  get-workspace-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get packages in workspace
        uses: caffco/yarn-workspace-pacakges-github-action@v1.0.0
        with:
          repository_path: .

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print packages
        needs: get-workspace-packages
        run: echo ${{ needs.get-workspace-packages.outputs.package_names }}

# jobs:
#   multiple:
#     # example with web application build,
#     # server start and waiting for the server
#     # to respond before running tests
#     # in each Yarn workspaces subfolder
#     runs-on: ubuntu-22.04
#     strategy:
#       # when one test fails, DO NOT cancel the other
#       # containers, because this will kill Cypress processes
#       # leaving the Cypress Cloud hanging ...
#       # https://github.com/cypress-io/github-action/issues/48
#       fail-fast: false
#       matrix:
#         cypress:
#           - working_directory: packages/backend
#             expected_endpoint: 'http://localhost:3000'
#           - working_directory: packages/frontend
#             expected_endpoint: 'http://localhost:3001'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Cypress tests
#         uses: ./
#         with:
#           working-directory: ${{ matrix.cypress.working_directory }}
#           build: yarn run build
#           start: yarn start
#           wait-on: 'http://localhost:5000'